wg-enroll: add logging and auto-detect default interface
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

diff --git a/.local/bin/wg-enroll b/.local/bin/wg-enroll
--- a/.local/bin/wg-enroll
+++ b/.local/bin/wg-enroll
@@ -18,8 +18,12 @@
 set -Eeuo pipefail
 
 function bail() {
-	echo "$@" >&2
+	echo "ERROR:" "$@" >&2
 	exit 2
+}
+
+function log() {
+	echo "INFO:" "$@" >&2
 }
 
 function usage() {
@@ -87,7 +91,7 @@ case "$OUTPUT" in
 		formatter=cat
 		;;
 	*)
-		bail "unknown formatter $OUTPUT"
+		bail "Unknown formatter $OUTPUT"
 		;;
 esac
 
@@ -96,8 +100,10 @@ local CONFIG="$CONFIG_ROOT/$CONFIG_NAME.conf"
 # If there is no config already there, we need to quickly set it up.
 if ! [ -f "$CONFIG" ]
 then
-	# XXX: Make this configuration less annoying.
-	HOST_NIC="${HOST_NIC:-eth0}"
+	# NOTE: This is kind of ugly to get the default interface. Should also be
+	#       configurable.
+	HOST_NIC="$(route -n | awk '$1 == "0.0.0.0" { print $8 }')"
+	log "Generating $CONFIG header (host_nic=$HOST_NIC)."
 	cat >"$CONFIG" <<-EOF
 	[Interface]
 	ListenPort = 51820
@@ -112,21 +118,22 @@ fi
 # round-trips or manual editing.
 if [ -z "$CLIENT_PUBKEY" ]
 then
+	log "No public key given (-P), generating new private key for client."
 	CLIENT_SECKEY="$(wg genkey)"
 	CLIENT_PUBKEY="$(wg pubkey <<<"$CLIENT_SECKEY")"
 fi
 local PRESHAREDKEY="$(wg genpsk)"
 
-[[ -n "$CLIENT_PUBKEY" ]] || bail "ERROR: Failed to generate public key using $CLIENT_SECKEY."
+[[ -n "$CLIENT_PUBKEY" ]] || bail "Failed to generate public key using $CLIENT_SECKEY."
 
 # TODO: Parse TOML properly...
 local NEW_DEVICEID="$(($(grep "\[Peer\]" "$CONFIG" | wc -l) + 1))"
 local SERVER_PUBKEY="$(grep "PrivateKey = " "$CONFIG" | sed -E 's/^[^=]*= (.*)$/\1/' | wg pubkey)"
 
 # Add to configuration.
+log "Updating $CONFIG for client (10.$NETWORKID.$NEW_DEVICEID.1)."
 (
-cat "$CONFIG"
-cat <<EOF
+cat "$CONFIG" - <<EOF
 
 # device-$NEW_DEVICEID.cyphar.com
 [Peer]
@@ -136,7 +143,16 @@ AllowedIPs = 10.$NETWORKID.$NEW_DEVICEID.1/32
 EOF
 ) | sponge "$CONFIG"
 
+# Ensure that ip_forward=1 is set.
+log "Ensuring net.ipv4.ip_forward is enabled."
+sysctl -w net.ipv4.ip_forward=1 >/dev/null || bail "Failed to set net.ipv4.ip_forward=1."
+
+# Update the configuration of the interface.
+log "Restarting host-side wireguard interface with new $CONFIG."
+systemctl restart "wg-quick@$CONFIG_NAME" || bail "Failed to restart wg-quick@$CONFIG_NAME"
+
 # Generate QR code for new device.
+printf "=== CONFIGURATION ===\n\n"
 "$formatter" <<EOF
 [Interface]
 Address = 10.$NETWORKID.$NEW_DEVICEID.1/16
